### ISSUE TITLE
[277] Support for custom html on slots

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/custom-html#1]
----
#cs: @santosguillamot
#supporter: @DAreRodz

https://frontity.pipedrive.com/deal/712
Site pageviews: **(0.91)**
Extra group sites: **(0)**
Extra group pageviews: **(0)**
Development size: **(3)**
Blocking: **no frontity without it (x15)**
Environment: **integration is finishing (x10)**
Reusability potential: **broad (x3)**
PRIORITY: **[277]**

**Comment by luisherranz** [comment]
We'll create a new package that saves the HTML in the database and uses `dangerouslyHTML` to inject it.

**Comment by luisherranz** [comment]
Use Custom Iframe as inspiration.
